Document: qt5-cinematic-experience
Title: Debian qt5-cinematic-experience Manual
Author: <insert document author here>
Abstract: This manual describes what qt5-cinematic-experience is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qt5-cinematic-experience/qt5-cinematic-experience.sgml.gz

Format: postscript
Files: /usr/share/doc/qt5-cinematic-experience/qt5-cinematic-experience.ps.gz

Format: text
Files: /usr/share/doc/qt5-cinematic-experience/qt5-cinematic-experience.text.gz

Format: HTML
Index: /usr/share/doc/qt5-cinematic-experience/html/index.html
Files: /usr/share/doc/qt5-cinematic-experience/html/*.html
